# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOauthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text=b'Access Token of the user which is used to access the content', max_length=255)),
                ('refresh_token', models.CharField(help_text=b'REfresh Token of the user used when Access Token expiers', max_length=255)),
                ('token_expiry', models.DateTimeField(help_text=b'Datetime when Access Token expires')),
                ('user', models.OneToOneField(help_text=b'User for whom token is generated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
