# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cal_id',
            field=models.CharField(default=1, help_text=b"Calender's ID", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(help_text=b'Title/Summary of the Calendar', max_length=500),
        ),
    ]
