# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar', '0002_auto_20191208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='rsvp',
            field=models.CharField(choices=[(b'needsAction', b'Needs Action'), (b'declined', b'Declined'), (b'tentative', b'Tentative'), (b'accepted', b'Accepted')], default=b'needsAction', help_text=b'RSVP of the Attendee', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(help_text=b'Link of Google Calendar Event', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together=set([('user', 'cal_id')]),
        ),
    ]
